### ISSUE TITLE
Reformat the templates

### ISSUE THREAD

**Issue by afuetterer** [ddionrails/ddionrails#126]
## templates
https://github.com/ddionrails/ddionrails/tree/master/templates

## app directories
- [x] concepts
- [x] data
- [x]  elastic
- [x] instruments
- [x] nav
- [x] pages
- [x] publications
- [x] questions
- [x] registration
- [x] studies
- [x] workspace

## main directory
- [x] 400.html
- [x] 403.html
- [x] 404.html
- [x] 500.html
- [x] base.html
- [x] base_basket.html
- [x] base_study.html
- [x] tracker.html

## TODO
- [x] add get_absolute_url method calls
- [x] add {% url %} template tags to call urls with parameters
- [x] integrate short template files
- [x] remove unused template files
- [ ] remove outdated title_de calls

**Comment by mpahl** [comment]
https://github.com/prettydiff/prettydiff/
Online Converter: https://prettydiff.com/?m=beautify

Prettydiff can identify django templates elements.
Metatags in HTML head have to be edited manually.

Example:
![prettydiff_1](https://user-images.githubusercontent.com/7721963/51117405-07253b00-180e-11e9-8a2c-337c34455e8d.png)

**Comment by afuetterer** [comment]
prettier.io does not support django templates yet: https://github.com/prettier/prettier/issues/5581

**Comment by mpahl** [comment]
https://github.com/beautify-web/js-beautify

js-beautify works but isn't optimized for django templates.
Metatags are detected but template code is handeld as text.

**Comment by afuetterer** [comment]
@mpahl : Please try this plugin for prettier.

https://github.com/prettier/prettier/issues/5581
https://github.com/robertquitt/prettier-plugin-djangohtml

**Comment by afuetterer** [comment]
@mpahl: What's the status of this?

**Comment by afuetterer** [comment]
That prettier-plugin-djangohtml is very much work in progress. Right now it is not usable.

**Comment by afuetterer** [comment]
PyCharm Professional can format Django templates.
